# Generated by Django 4.1.7 on 2023-04-01 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("duration", models.DurationField()),
                ("startdate", models.DateField()),
                ("completiondate", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "uncompleted"), (1, "completed")], default=0
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
